[package]

name = "osmxml"
version = "0.0.1"
authors = ["Matthew Hall <matthew@quickbeam.me.uk>"]

[lib]
name = "osmxml"
path = "src/lib.rs"

[[example]]
name = "spa"
path = "examples/main.rs"

[dependencies.rust-xml]
git = "https://github.com/netvl/rust-xml.git"
